// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_spaceship = "CgkImqGu0fgUEAIQEQ"; // <GPGSID>
        public const string achievement_20000 = "CgkImqGu0fgUEAIQAw"; // <GPGSID>
        public const string achievement_50000 = "CgkImqGu0fgUEAIQBg"; // <GPGSID>
        public const string achievement_500000 = "CgkImqGu0fgUEAIQDQ"; // <GPGSID>
        public const string achievement_character_open = "CgkImqGu0fgUEAIQEg"; // <GPGSID>
        public const string achievement_pyramid_door_2_open = "CgkImqGu0fgUEAIQGA"; // <GPGSID>
        public const string achievement_apart_door_1_open = "CgkImqGu0fgUEAIQFQ"; // <GPGSID>
        public const string achievement_spaceship_door_2_open = "CgkImqGu0fgUEAIQHg"; // <GPGSID>
        public const string achievement_submarine_door_3_open = "CgkImqGu0fgUEAIQHA"; // <GPGSID>
        public const string achievement_character_open_2 = "CgkImqGu0fgUEAIQEw"; // <GPGSID>
        public const string achievement_character_open_3 = "CgkImqGu0fgUEAIQFA"; // <GPGSID>
        public const string achievement_10000 = "CgkImqGu0fgUEAIQBQ"; // <GPGSID>
        public const string achievement_submarine = "CgkImqGu0fgUEAIQEA"; // <GPGSID>
        public const string achievement_pyramid_door_1_open = "CgkImqGu0fgUEAIQFw"; // <GPGSID>
        public const string achievement_1000 = "CgkImqGu0fgUEAIQAg"; // <GPGSID>
        public const string achievement_spaceship_door_1_open = "CgkImqGu0fgUEAIQHQ"; // <GPGSID>
        public const string achievement_submarine_door_2_open = "CgkImqGu0fgUEAIQGw"; // <GPGSID>
        public const string achievement_300000 = "CgkImqGu0fgUEAIQDA"; // <GPGSID>
        public const string leaderboard_score = "CgkImqGu0fgUEAIQCg"; // <GPGSID>
        public const string achievement_30000 = "CgkImqGu0fgUEAIQBw"; // <GPGSID>
        public const string achievement_submarine_door_1_open = "CgkImqGu0fgUEAIQGg"; // <GPGSID>
        public const string achievement_pyramid = "CgkImqGu0fgUEAIQDw"; // <GPGSID>
        public const string achievement_pyramid_door_3_open = "CgkImqGu0fgUEAIQGQ"; // <GPGSID>
        public const string achievement_7500 = "CgkImqGu0fgUEAIQBA"; // <GPGSID>
        public const string achievement_1000000 = "CgkImqGu0fgUEAIQDg"; // <GPGSID>
        public const string achievement_100000 = "CgkImqGu0fgUEAIQCA"; // <GPGSID>
        public const string achievement_apart_door_2_open = "CgkImqGu0fgUEAIQFg"; // <GPGSID>
        public const string achievement_spaceship_door_3_open = "CgkImqGu0fgUEAIQHw"; // <GPGSID>

}

